# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THp-fGH-KuSX4cu41hxxsnz_i0fP6ukN
"""

print("Hello World")